title: PineAPPL
email: christopher.schwan@mi.infn.it
description: "PineAPPL is not an extension of APPLgrid."
show_downloads: false
baseurl: "/pineappl"
url: "https://n3pdf.github.io"

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman